# Bloodborne 
bb_creatures = [
	"Beast",
	"Man-beast",
	"Giant beast",
	"Abhorrent beast",
	"Infected one",
	"Foe",
	"Strong foe",
	"Giant foe",
	"Terrible foe",
	"Hound",
	"Bird",
	"Snake",
	"Animal",
	"Insect",
	"Watcher",
	"Shaman",
	"Dead",
	"Foul spirit",
	"The lost",
	"Malformed thing",
	"Monster",
	"Unknown thing",
	"Slimy thing",
	"Blobby thing",
	"Kin of the cosmos",
	"Evil eye",
	"False god",
	"Superior being",
	"Messenger",
	"Doll"
	]

bb_humans = [
	"Man",
	"Woman",
	"Elderly",
	"Ailing one",
	"Madman",
	"Keeper",
	"Mob",
	"Wheelchair",
	"Small gent",
	"Small lady",
	"Titan",
	"Amazon",
	"Fatty",
	"Dullard",
	"Liar",
	"Scoundrel",
	"Child",
	"Friend",
	"Darling",
	"Master",
	"Infant",
	"Queen",
	"Yourself",
	"Hunter",
	"Co-operator",
	"Adversary",
	"Executioner",
	"Vileblood",
	"Hunter of hunters",
	"Blood-addled hunter"]

bb_tactics_a = [
	"Physical attack",
	"Blunt attack",
	"Thrust attack",
	"Blood attack",
	"Arcane",
	"Fire",
	"Bolt",
	"Quick weapon",
	"Long weapon",
	"Poison",
	"Frenzy",
	"Exploiting species",
	"Beast transformation",
	"Firearm",
	"Blunderbuss",
	"Torch",
	"Shield",
	"Rally",
	"Charge attack",
	"Visceral attack",
	"Rolling",
	"Quickstep",
	"Blood vial",
	"Quicksilver Bullet",
	"Medicine",
	"Special medicine",
	"Projectile",
	"Oil",
	"Coarse paper",
	"Special item"]

bb_tactics_b = [
	"Ambush",
	"Pincer attack",
	"Sneak attack",
	"Patrol",
	"Reinforcements caller",
	"\"Focus on attacks\"",
	"\"Focus on evasion\"",
	"\"Focus on healing\"",
	"\"Close-range fight\"",
	"\"Long-range fight\"",
	"\"Hit-and-run\"",
	"Sniping",
	"Counter",
	"\"Attack from behind\"",
	"\"Open when attacking\"",
	"\"Strike and be struck\"",
	"\"Kill in order\"",
	"\"Kill first\"",
	"Charging forth",
	"Lure",
	"Stealth",
	"Ignoring",
	"Retreat",
	"Use of terrain",
	"Tight spot",
	"High spot",
	"Fall",
	"Alertness",
	"Unbreakable will",
	"Leaden constitution"]

bb_places_things = [
	"Blood Echoes",
	"Insight",
	"Blood stone",
	"Blood Gem",
	"Rune",
	"Ritual material",
	"Key",
	"Item",
	"Special item",
	"Paleblood",
	"Message",
	"Rating",
	"Dead body",
	"Treasure",
	"Lever",
	"Statue",
	"Light",
	"Bonfire",
	"Footing",
	"Trap",
	"Yharnam",
	"Clinic",
	"Grand Cathedral",
	"Church",
	"Safe place",
	"Old labyrinth",
	"Workshop",
	"Healing Church",
	"Hidden path",
	"Unseen Village"]

bb_concepts = [
	"Hunting",
	"Night",
	"Dawn",
	"Blood",
	"Warm blood",
	"Scourge",
	"Life",
	"Nightmare",
	"Moon",
	"Cosmos",
	"Eye",
	"Oedon",
	"Communion",
	"Donation",
	"Ritual",
	"Contact",
	"Encounter",
	"Evolution",
	"Oath",
	"Corruption",
	"Execution",
	"Cleansing",
	"Prayer",
	"Curse",
	"Defilement",
	"Sinister",
	"Courage",
	"Respect",
	"Inquisitiveness",
	"Pity",
	"Grief",
	"Joy",
	"Wrath",
	"Sanity",
	"Madness",
	"Fervour",
	"Seduction",
	"Feasting",
	"Tastiness",
	"Tonsil",
	"Metamorphosis",
	"Common sense",
	"Darkness",
	"Secret",
	"Singing",
	"Sobbing",
	"Howling",
	"\"All's well\"",
	"The unseen",
	"All"]

bb_templates = [
	"fear {0}", 
	"remember {0}",
	"time for {0}",
	"it's the scourge of {0}",
	"reeks of {0}",
	"{0} is effective",
	"beware of {0}",
	"treat {0} with care",
	"it is all thanks to {0}",
	"despicable {0}",
	"woeful {0}",
	"wondrous {0}",
	"nothing but {0} here",
	"{0} waits ahead",
	"you must accept {0}",
	"have mercy, {0}",
	"no mercy for {0}",
	"have audience with {0}",
	"reminiscent of {0}",
	"oh, {0}!",
	"you've come to the right place",
	"bless us with blood",
	"may the good blood guide your way",
	"fear your blindness",
	"the sky and the cosmos are one",
	"let us cleanse these foul streets",
	"you're in the know, right?",
	"oh, I can't wait... hee hee...",
	"take a step forward",
	"turn back",
	"those with faith will be spared",
	"don't be fooled",
	"pitiful, really",
	"behind you",
	"don't you dare look at me!",
	"sincerest thanks",
	"a hunter is never alone",
	"please, carry on in my stead",
	"run!",
	"don't give up!"
	]

bb_conjunctions = [
	"\nand ",
	"\nbut ",
	"\nor ",
	"\ntherefore ",
	"\neventually ",
	",\n"]